---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cloud.seayun.com
  resources:
  - virtuakmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.seayun.com
  resources:
  - virtuakmachines/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.seayun.com
  resources:
  - virtuakmachines/status
  verbs:
  - get
  - patch
  - update
